name: LiteAnnouncer
version: 1.1.5
author: TRCStudioDean
main: studio.trc.bukkit.liteannouncer.Main
api-version: 1.13
softdepend: [PlaceholderAPI]
commands:
    la:
        description: 'LiteAnnouncer main command.'
        aliases: [liteannouncer]